In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\yhk25\.conda\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
df.head()

        job_title_short  ...                                    job_type_skills
0  Senior Data Engineer  ...                                                NaN
1          Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2         Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3         Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4         Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...

[5 rows x 17 columns]

In [4]:
df.tail()

          job_title_short  ...                                    job_type_skills
785736  Software Engineer  ...  {'os': ['linux', 'unix'], 'other': ['kubernete...
785737       Data Analyst  ...  {'analyst_tools': ['sas', 'excel'], 'programmi...
785738   Business Analyst  ...         {'analyst_tools': ['powerpoint', 'excel']}
785739      Data Engineer  ...  {'cloud': ['aws', 'snowflake', 'azure', 'redsh...
785740  Software Engineer  ...              {'cloud': ['aws'], 'other': ['flow']}

[5 rows x 17 columns]

In [11]:
df.sample(10)

             job_title_short  ...                                    job_type_skills
465380   Senior Data Analyst  ...  {'analyst_tools': ['ssis'], 'cloud': ['azure']...
730419          Data Analyst  ...  {'analyst_tools': ['power bi'], 'cloud': ['sno...
129793        Data Scientist  ...  {'cloud': ['snowflake', 'aws'], 'programming':...
490769         Data Engineer  ...  {'cloud': ['aws', 'snowflake'], 'libraries': [...
34788         Cloud Engineer  ...  {'cloud': ['gcp', 'snowflake', 'aws'], 'librar...
593346  Senior Data Engineer  ...  {'cloud': ['gcp', 'aws'], 'databases': ['postg...
14229          Data Engineer  ...  {'cloud': ['aws', 'gcp', 'azure', 'databricks'...
278316        Data Scientist  ...                                                NaN
1583          Data Scientist  ...  {'analyst_tools': ['sas', 'ssis', 'ssrs'], 'cl...
312025          Data Analyst  ...  {'analyst_tools': ['excel'], 'programming': ['...

[10 rows x 17 columns]

In [9]:
df.sample(10, random_state=42)

              job_title_short  ...                                    job_type_skills
502901   Senior Data Engineer  ...  {'cloud': ['azure'], 'other': ['git'], 'progra...
406337  Senior Data Scientist  ...  {'analyst_tools': ['looker'], 'cloud': ['bigqu...
659951          Data Engineer  ...                                                NaN
541593           Data Analyst  ...                                {'async': ['jira']}
425158   Senior Data Engineer  ...                        {'programming': ['python']}
183426           Data Analyst  ...  {'analyst_tools': ['tableau'], 'cloud': ['orac...
287790           Data Analyst  ...  {'analyst_tools': ['excel'], 'libraries': ['ha...
541983           Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau', 'qli...
416896         Data Scientist  ...                                                NaN
780907          Data Engineer  ...  {'analyst_tools': ['alteryx'], 'cloud': ['orac...

[10 rows x 17 columns]

In [2]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

In [14]:
df_altered = df_original

median_salary = df_altered['salary_year_avg'].median()

In [16]:
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

df_altered.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [17]:
df_original.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [18]:
id(df_original)

1773547257296

In [19]:
id(df_altered)

1773547257296

In [20]:
id(df_original) == id(df_altered)

True

In [3]:
df_altered = df_original.copy()

In [5]:
print('ID of df_original:', id(df_original))
print('ID df df_altered:', id(df_altered))
print("Are the two dataframes the same?:", id(df_altered) == id(df_original))

ID of df_original: 2514037755856
ID df df_altered: 2514037643920
Are the two dataframes the same?: False

In [6]:
median_salary = df_altered['salary_year_avg'].median()
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

df_altered.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [7]:
df_original.loc[:5, 'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

In [9]:
df_original.sample(frac = 0.01, replace = False)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
46211,Senior Data Analyst,Customer Analytics Senior Manager,Ireland,via BeBee Ireland,Full-time,False,Ireland,2023-11-19 06:32:14,True,False,Ireland,NaN,NaN,NaN,PricewaterhouseCoopers International Limited,NaN,NaN
439896,Data Analyst,Research Data Analyst,"San Francisco, CA",via BeBee,Full-time,False,"California, United States",2023-03-02 16:01:40,False,False,United States,NaN,NaN,NaN,University of California - San Francisco Campu...,"['outlook', 'word', 'powerpoint', 'excel']","{'analyst_tools': ['outlook', 'word', 'powerpo..."
204793,Data Engineer,Principal Data Engineer (data applications/clo...,"Boston, MA",via Snagajob,Full-time,False,"Florida, United States",2023-06-14 22:10:42,False,False,United States,NaN,NaN,NaN,Liberty Mutual,"['python', 'sql', 'aws', 'snowflake', 'react',...","{'cloud': ['aws', 'snowflake'], 'libraries': [..."
111382,Data Engineer,Software Data Engineer - SAP,United Kingdom,via Recruit.net,Full-time,False,United Kingdom,2023-08-13 00:16:57,True,False,United Kingdom,NaN,NaN,NaN,Bell Integration,"['javascript', 'groovy', 'sql', 'azure', 'reac...","{'analyst_tools': ['sap'], 'cloud': ['azure'],..."
705216,Data Analyst,SQL Data Analyst,"Northampton, UK",via Indeed,Full-time,False,United Kingdom,2023-01-24 03:13:00,True,False,United Kingdom,NaN,NaN,NaN,Identifi Global,"['sql', 'vba', 'power bi', 'ssis', 'excel']","{'analyst_tools': ['power bi', 'ssis', 'excel'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377692,Data Analyst,Research/Data Analyst-P20W - Full-time / Part-...,"Jefferson City, MO",via Snagajob,Full-time,False,"Illinois, United States",2023-07-27 18:02:19,False,True,United States,NaN,NaN,NaN,Saint Louis County Clerks Office,"['sas', 'sas', 'r', 'sql', 'tableau']","{'analyst_tools': ['sas', 'tableau'], 'program..."
12296,Data Scientist,"Associate Data Scientist, PRM",United States,via Trabajo.org,Full-time,False,"Texas, United States",2023-03-10 13:07:17,False,False,United States,NaN,NaN,NaN,Frontier Airlines,NaN,NaN
573545,Data Analyst,"datenanalyst, data analyst","Nuremberg, Germany",via BeBee,Full-time,False,Germany,2023-09-09 09:11:38,True,False,Germany,NaN,NaN,NaN,GOLDMANN Personaldienste - Inci Kaygisuz,NaN,NaN
319348,Data Scientist,Data Science and Machine Learning Matching Spe...,"Buenos Aires, Argentina","via Trabajo.org - Vacantes De Empleo, Trabajo",Full-time,False,Argentina,2023-06-06 17:31:04,False,False,Argentina,NaN,NaN,NaN,Andela,NaN,NaN
79172,Data Analyst,Growth data analyst,Argentina,via Sercanto,Full-time,False,Argentina,2023-04-06 00:18:24,True,False,Argentina,NaN,NaN,NaN,Slite,NaN,NaN

## Problem

In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\yhk25\.conda\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df_cleaned = df.dropna(subset = ['salary_year_avg'])

In [7]:
df.sample(n = 1000, random_state = 42)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,NaN,NaN,NaN,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,NaN,NaN,NaN,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,NaN,NaN,NaN,Morgan King,NaN,NaN
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,NaN,NaN,NaN,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,NaN,NaN,NaN,Independent Recruiters,['python'],{'programming': ['python']}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398992,Business Analyst,Commercial Sales Analyst,"Kampala, Uganda",via LinkedIn Uganda,Internship,False,Uganda,2023-06-27 19:44:18,False,False,Uganda,NaN,NaN,NaN,M-KOPA,"['r', 'python', 'sql', 'excel', 'dax', 'power ...","{'analyst_tools': ['excel', 'dax', 'power bi',..."
626660,Data Analyst,Sr Data Analyst,"Austin, TX",via Trabajo.org,Full-time,False,"Texas, United States",2023-08-11 12:01:40,True,False,United States,NaN,NaN,NaN,Alliance Animal Health,"['sql', 'python', 'redshift', 'tableau', 'exce...","{'analyst_tools': ['tableau', 'excel'], 'cloud..."
127988,Data Scientist,Data Scientist Product Development Associate M...,"Fort Worth, TX",via Texas Jobs - Tarta.ai,Full-time,False,Sudan,2023-03-04 08:35:08,False,False,Sudan,NaN,NaN,NaN,Lockheed Martin,"['sas', 'sas', 'r', 'python', 'matlab', 'sql',...","{'analyst_tools': ['sas', 'tableau'], 'librari..."
506435,Data Engineer,Trainee (m/w/d) Data Engineer,"Rödental, Germany",via BeBee,Full-time,False,Germany,2023-10-11 11:14:00,False,False,Germany,NaN,NaN,NaN,AOK Baden-Württemberg,"['sql', 'python', 'c', 'c++', 'java']","{'programming': ['sql', 'python', 'c', 'c++', ..."
675454,Data Scientist,Data Scientist / Data Engineer (a). Job in Thu...,"Thun, Switzerland",via NBC4i Jobs,Full-time,False,Switzerland,2023-05-09 11:28:40,False,False,Switzerland,NaN,NaN,NaN,Nexus,"['python', 'sql', 'qlik']","{'analyst_tools': ['qlik'], 'programming': ['p..."

In [9]:
df.sample(frac = 0.1)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
171897,Senior Data Engineer,Senior Manager-Data Engineering,"Dublin, Ireland",via BeBee Ireland,Full-time,False,Ireland,2023-01-18 15:29:40,False,False,Ireland,NaN,NaN,NaN,RealTime Recruitment Limited,NaN,NaN
91320,Data Scientist,Data Scientist,"Edinburgh, UK",via Recruit.net,Full-time,False,United Kingdom,2023-01-22 00:21:12,False,False,United Kingdom,NaN,NaN,NaN,Natwest,NaN,NaN
562933,Data Scientist,"Data Scientist, Liveanalytics","Phoenix, AZ",via BeBee,Full-time,False,Sudan,2023-03-14 04:57:58,False,True,Sudan,NaN,NaN,NaN,Live Nation,"['sql', 'python', 'flow', 'confluence']","{'async': ['confluence'], 'other': ['flow'], '..."
199840,Data Analyst,IT Operations Analyst - Cyber Security Services,"Otopeni, Romania",via LinkedIn,Full-time,False,Romania,2023-10-04 15:20:42,False,False,Romania,NaN,NaN,NaN,Stefanini EMEA,NaN,NaN
533922,Data Engineer,Snowflake Data Engineer,United Kingdom,via KSNT Jobs,Full-time,False,United Kingdom,2023-05-28 19:12:26,True,False,United Kingdom,NaN,NaN,NaN,Click Digital,"['snowflake', 'azure']","{'cloud': ['snowflake', 'azure']}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596606,Data Analyst,Trabalhe de Casa Data Analytics,Brazil,via BeBee,Full-time,False,Brazil,2023-09-06 09:45:25,False,False,Brazil,NaN,NaN,NaN,BairesDev,"['sql', 'python', 'r', 'spark', 'hadoop']","{'libraries': ['spark', 'hadoop'], 'programmin..."
244278,Data Engineer,Data engineer,"Tallinn, Estonia",via LinkedIn,Full-time,False,Estonia,2023-07-19 07:38:47,True,False,Estonia,NaN,NaN,NaN,Atrium HR Consulting,"['go', 'sql', 'python', 'scala', 'java', 'bigq...","{'cloud': ['bigquery', 'databricks'], 'librari..."
161962,Data Engineer,Traveling Data Engineer,"Hopewell, FL",via BeBee,Full-time,False,"Florida, United States",2023-12-17 15:08:33,False,False,United States,NaN,NaN,NaN,Peraton,"['python', 'sql', 'java', 'r', 'aws', 'azure',...","{'analyst_tools': ['excel'], 'cloud': ['aws', ..."
615528,Data Scientist,Need Senior Data Scientist Tech Lead Position ...,Anywhere,via Upwork,Contractor,True,"Texas, United States",2023-03-08 12:03:57,False,False,United States,NaN,NaN,NaN,Upwork,"['sql', 'aws', 'redshift', 'tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi'], 'cl..."
498408,Data Engineer,Data Network Engineer,Singapore,via LinkedIn,Full-time,False,Singapore,2023-07-20 11:18:23,False,False,Singapore,NaN,NaN,NaN,Smart IMS Inc.,"['shell', 'perl', 'python']","{'programming': ['shell', 'perl', 'python']}"

In [10]:
df_copy = df.copy()

median_salary = df_copy['salary_year_avg'].median()
df_copy['salary_year_avg'] = df_copy['salary_year_avg'].fillna(median_salary)